//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechTestAPI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TechTestAPI.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///URL           =&gt;{3}
        ///Parameters    =&gt;Name: {0}, Value: {1}, Parameter Type: {2}
        ///Response Body =&gt;{4}
        ///
        ///Error Message =&gt;Yukarıdaki bilgiler ile &apos;{1}&apos; search yapıldı. 
        ///Dönen sonuçlardan ismi &apos;{5}&apos; olan filmin Imdb id si alınıp Search By ImdbId yapıldı. 
        ///Dönen response da &apos;{6}&apos; degeri boştu!.
        /// </summary>
        public static string Detail_Control_Error_Message {
            get {
                return ResourceManager.GetString("Detail_Control_Error_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///URL           =&gt;{3}
        ///Parameters    =&gt;Name: {0}, Value: {1}, Parameter Type: {2}
        ///Response Body =&gt;{4}
        ///
        ///Error Message =&gt;Yukarıdaki bilgiler ile Get istegi atıldı ancak beklenen Status code dönmedi!
        ///.
        /// </summary>
        public static string HTTP_Status_Error_Message {
            get {
                return ResourceManager.GetString("HTTP_Status_Error_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Method Name: {0}
        ///URL:{1}
        ///Header{2}
        ///Request Body (If There Is):{3}
        ///Response Body (If There Is):{4}
        ///Error Message:{4}.
        /// </summary>
        public static string Log_Messages {
            get {
                return ResourceManager.GetString("Log_Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///URL           =&gt;{3}
        ///Parameters    =&gt;Name: {0}, Value: {1}, Parameter Type: {2}
        ///Response Body =&gt;{4}
        ///
        ///Error Message =&gt;Yukarıdaki bilgiler ile Search By Imdb yapıldı. Dönen response dan imdb ıd alınıp karşılaştırıldı ancak beklenildiği gibi değildi!.
        /// </summary>
        public static string Search_By_IMDBId_Error_Message {
            get {
                return ResourceManager.GetString("Search_By_IMDBId_Error_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///URL           =&gt;{3}
        ///Parameters    =&gt;Name: {0}, Value: {1}, Parameter Type: {2}
        ///Response Body =&gt;{4}
        ///
        ///Error Message =&gt;Yukarıdaki bilgiler ile Get istegi atıldı ancak dönen title lar içerisinde &apos;{5}&apos; geçmeyen bir data vardı!
        ///Title ı beklenildiği gibi olmayan data =&gt;{6}.
        /// </summary>
        public static string Title_Control_Error_Message {
            get {
                return ResourceManager.GetString("Title_Control_Error_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///URL           =&gt;{3}
        ///Parameters    =&gt;Name: {0}, Value: {1}, Parameter Type: {2}
        ///Response Body =&gt;{4}
        ///
        ///Error Message =&gt;Yukarıdaki bilgiler ile &apos;{1}&apos; search yapıldı. 
        ///Ancak dönen sonuçlardan ismi &apos;{5}&apos; olan bir data bulunamadı!..
        /// </summary>
        public static string Wanted_Result_Control_Error_Message {
            get {
                return ResourceManager.GetString("Wanted_Result_Control_Error_Message", resourceCulture);
            }
        }
    }
}
